[package]
name = "untitled-programming-language-project"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uplp"
path = "src/bin/uplp.rs"

[lib]

[build-dependencies]
lalrpop = "0.19.8"

[dependencies]
lalrpop-util = { version = "0.19.8", features = ["lexer"] }

[dev-dependencies]
rand = "0.8.5"